/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Landan
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NotesDirectory = new javax.swing.JDialog();
        NoteEditing = new javax.swing.JFrame();
        newNote = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        notesCollection = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        flashcards = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        notesLabel = new javax.swing.JLabel();

        NotesDirectory.setTitle("NotesDirectory");

        javax.swing.GroupLayout NotesDirectoryLayout = new javax.swing.GroupLayout(NotesDirectory.getContentPane());
        NotesDirectory.getContentPane().setLayout(NotesDirectoryLayout);
        NotesDirectoryLayout.setHorizontalGroup(
            NotesDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        NotesDirectoryLayout.setVerticalGroup(
            NotesDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        NoteEditing.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        NoteEditing.setTitle("NoteEditing");

        javax.swing.GroupLayout NoteEditingLayout = new javax.swing.GroupLayout(NoteEditing.getContentPane());
        NoteEditing.getContentPane().setLayout(NoteEditingLayout);
        NoteEditingLayout.setHorizontalGroup(
            NoteEditingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        NoteEditingLayout.setVerticalGroup(
            NoteEditingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        NoteEditing.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newNote.png"))); // NOI18N
        newNote.setText("newNote");
        newNote.setInheritsPopupMenu(true);
        newNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newNoteMousePressed(evt);
            }
        });
        newNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNoteActionPerformed(evt);
            }
        });

        jLabel1.setText("NEW NOTE");

        notesCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filingCabinet.png"))); // NOI18N
        notesCollection.setText("notesCollection");
        notesCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesCollectionActionPerformed(evt);
            }
        });

        jLabel2.setText("SEE NOTES COLLECTION");

        flashcards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flashCards.png"))); // NOI18N
        flashcards.setText("flashcards");
        flashcards.setInheritsPopupMenu(true);
        flashcards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashcardsActionPerformed(evt);
            }
        });

        jLabel3.setText("FLASHCARDS");

        notesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notesLabel.setText("Java Notes App");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(newNote, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(notesCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(flashcards, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(notesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(notesLabel)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNote, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notesCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flashcards, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        notesLabel.getAccessibleContext().setAccessibleName("notesLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNoteActionPerformed
        
    }//GEN-LAST:event_newNoteActionPerformed

    private void notesCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesCollectionActionPerformed
       
    }//GEN-LAST:event_notesCollectionActionPerformed

    private void flashcardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashcardsActionPerformed
       
    }//GEN-LAST:event_flashcardsActionPerformed

    private void newNoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newNoteMousePressed
        // TODO add your handling code here:
         NoteEditing.setTitle("New Note");
         NoteEditing.setSize(400, 300);
         NoteEditing.setLocationRelativeTo(this); // Center it on the parent window
         NoteEditing.setVisible(true);
    }//GEN-LAST:event_newNoteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame NoteEditing;
    private javax.swing.JDialog NotesDirectory;
    private javax.swing.JButton flashcards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newNote;
    private javax.swing.JButton notesCollection;
    private javax.swing.JLabel notesLabel;
    // End of variables declaration//GEN-END:variables
}
